### ISSUE TITLE
Should the input matrix be KR normalized ?

### ISSUE THREAD

**Issue by shenscore** [ChenFengling/HiCDB#1]
Hi Fengling,

    What kind of input should I use with HiCDB? a KR normalized matrix or raw contact matrix ?

Thanks,
Shenwie.

**Comment by ChenFengling** [comment]
Both is OK， we will  test the data for normalized or not. If it is not normalized, the KR normalization will be performed in the function.

**Comment by shenscore** [comment]
OK, Thanks!
